services:
  - type: web
    name: krishta-pharma
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: krishta-pharma-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: krishta-pharma-db
    plan: free
